[tools]
bat = "latest"
bottom = "latest"
bun = "latest"
fzf = "latest"
gh = "latest"
ghq = "latest"
go = "latest"
hunk = "latest"
lazygit = "latest"
neovim = "0.11.7"
node = "latest"
python = "latest"
ripgrep = "latest"
uv = "latest"
