# color from tokyo-night
#status-window "#737aa2"

#non-active-gray "#2f334d"
#active-green "#41a6b5"

#base-background "#1a1b26"
#base-white "#eeeeee"
#base-white-gray "#e4e4e4"
#base-gray "#454545"
#base-dark-gray "#303030"
#base-black "#121212"

# プラグインマネージャーを導入
setenv -g TMUX_PLUGIN_MANAGER_PATH "$HOME/.tmux/plugins/"

# tpm がなければ clone して install
if-shell "[ ! -d '$HOME/.tmux/plugins/tpm' ]" \
  'run-shell "git clone https://github.com/tmux-plugins/tpm $HOME/.tmux/plugins/tpm && $HOME/.tmux/plugins/tpm/bin/install_plugins"'

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'

#pluginを適用,プラグインの設定はこの上に書く
run '~/.tmux/plugins/tpm/tpm'

# prefixキーをC-qに変更
unbind C-b
set -g prefix C-g

# キーストロークのディレイを減らす
set -sg escape-time 1

# windowのインデックスを1から始める
set -g base-index 1

# paneのインデックスを1から始める
setw -g pane-base-index 1

# PaneをVim-likeに移動する
bind -r k select-pane -U 
bind -r j select-pane -D 
bind -r h select-pane -L 
bind -r l select-pane -R

#True Colorが出るように
set-option -g default-terminal "tmux-256color"
set-option -ga terminal-overrides ",xterm-256color:Tc"

# ステータスバーの色を設定する
set -g status-style "bg=#1a1b26,fg=#303030"

# ステータスバーの左側に表示
# setw -g status-left '#(sh -c "echo 󰚩  󱚝  󱚟  󱚡  󱚣  󱜙  󱚥 | tr \" \" \"\n\" | shuf -n 1 | sed \"s/^/　/; s/$/　/\"")'
setw -g status-left ""

# window-status のフォーマットを指定する
set -g status-justify centre
setw -g window-status-format " #I: #W #{?window_bell_flag,  ,}"

# bellが鳴ったときのスタイルを変更
setw -g window-status-bell-style "bg=#1a1b26,fg=#303030,bold"

# カレントウィンドウの window-status のフォーマットを指定する
setw -g window-status-current-format "\
#[fg=#737aa2, bg=#1a1b26]\
#[fg=#e4e4e4, bg=#737aa2]   #W \
#[fg=#737aa2, bg=#1a1b26]"

# ステータスバーの右側の表示内容を空に設定
set -g status-right-length 60 
setw -g status-right "#{?client_prefix,#[fg=#9ece6a]󰊴  v>nvim g>lazygit \%>splitH \">splitV ,#[fg=#e4e4e4]󰍎 YAMAGATA/JAPAN 󰃭 %y-%m-%d %a  %H:%M}"

# ベルの音を消す
set -g bell-action none
# setw -g window-status-bell-style "none"

# 非アクティブpaneのスタイル
set -g window-style "fg=#454545, dim"
set -g pane-border-style "fg=#2f334d, dim"

# アクティブpaneのスタイル
set -g window-active-style "fg=#e4e4e4, bg=#1a1b26"
#set -g pane-active-border-style "fg=#41a6b5, bold"
set -g pane-active-border-style "fg=#737aa2, bold"

# borderのスタイルを変更
set -g pane-border-lines single 

set -g pane-border-status top
set -g pane-border-format " #P: #{pane_current_command} "

# ヴィジュアルノーティフィケーションを無効にする
# setw -g monitor-activity off
# set -g visual-activity off

# checkhealth回避用
set -g escape-time 10
set -g focus-events on

#マウス操作を有効にする
set -g mouse on
#コピーモード時のキーバインドをVimに
setw -g mode-keys vi

# 新規paneでも同じディレクトリになるように
bind '"' split-window -v -c "#{pane_current_path}"
bind %   split-window -h -c "#{pane_current_path}"

# tmuxのコピーモードからクリップボードにコピー
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind-key -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "xsel -bi"
bind-key -T copy-mode-vi Enter send-keys -X copy-pipe-and-cancel "xsel -bi"

#Ctrl-g bでpopupを立ち上げる
bind b display-popup -E -w 90% -h 90% -d "#{pane_current_path}"

#Ctrl-g gでlazygitをpopupで立ち上げる
bind g display-popup -E -w 90% -h 90% -d "#{pane_current_path}" "lazygit"

#Ctrl-g vでnvimをpopupで立ち上げる
bind v display-popup -E -w 90% -h 90% -d "#{pane_current_path}" "nvim ."

